<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE datos_wiki [
    <!ELEMENT datos_wiki (usuarios, mods)>
    <!ELEMENT usuarios (usuario+)>
    <!ELEMENT usuario (nickname, password)>
    <!ELEMENT nickname (#PCDATA)>
    <!ELEMENT password (#PCDATA)>
    <!ELEMENT mods (mod+)>
    <!ELEMENT mod (nombre, categoria, dificultad)>
    <!ELEMENT nombre (#PCDATA)>
    <!ELEMENT categoria (#PCDATA)>
    <!ELEMENT dificultad (#PCDATA)>
]>
<datos_wiki>
    <usuarios>
        <usuario>
            <nickname>admin</nickname>
            <password>12345</password>
        </usuario>
        <usuario>
            <nickname>antonio</nickname>
            <password>listi2026</password>
        </usuario>
    </usuarios>

    <mods>
        <mod>
            <nombre>DeceasedCraft</nombre>
            <categoria>Supervivencia</categoria>
            <dificultad>Extrema</dificultad>
        </mod>
        <mod>
            <nombre>Cobblemon</nombre>
            <categoria>Aventura</categoria>
            <dificultad>Media</dificultad>
        </mod>
        <mod>
            <nombre>Alex's Caves</nombre>
            <categoria>Exploración</categoria>
            <dificultad>Alta</dificultad>
        </mod>
        <mod>
            <nombre>RLCraft</nombre>
            <categoria>Supervivencia Hardcore</categoria>
            <dificultad>Extrema</dificultad>
        </mod>
        <mod>
            <nombre>Create</nombre>
            <categoria>Ingeniería</categoria>
            <dificultad>Media</dificultad>
        </mod>
        <mod>
            <nombre>Twilight Forest</nombre>
            <categoria>Aventura</categoria>
            <dificultad>Media</dificultad>
        </mod>
    </mods>
</datos_wiki>